-- colors generated by matugen

return {
    background = "{{colors.surface.default.hex}}",
    on_background = "{{colors.on_surface.default.hex}}",
    primary = "{{colors.primary.default.hex}}",
    on_primary = "{{colors.on_primary.default.hex}}",
    secondary = "{{colors.secondary.default.hex}}",
    on_secondary = "{{colors.on_secondary.default.hex}}",
    container = "{{colors.surface_container.default.hex}}",
    on_container = "{{colors.on_surface.default.hex}}",
}
