hl.config({
    general = {
        border_size = 2,
        gaps_in = 5,
        gaps_out = 5,
        float_gaps = 0,
        gaps_workspaces = 0,
        layout = "dwindle",
        no_focus_fallback = false,
        resize_on_border = true,
        extend_border_grab_area = 5,
        hover_icon_on_border = true,
        allow_tearing = false,
        resize_corner = 0,
        modal_parent_blocking = true,
        snap = {
            enabled = true,
            window_gap = 5,
            monitor_gap = 5,
            border_overlap = false,
            respect_gaps = true
        },
    },
    decoration = {
        rounding = 5,
        rounding_power = 4,
        active_opacity = 1.00,
        inactive_opacity = 0.90,
        fullscreen_opacity = 1.00,
        dim_modal = true,
        dim_inactive = true,
        dim_strength = 0.10,
        dim_special = 0.40,
        dim_around = 0.00,
        border_part_of_window = true,
        blur = {
            enabled = true,
            size = 5,
            passes = 3,
            ignore_opacity = false,
            new_optimizations = true,
            xray = false,
            noise = 0.00,
            contrast = 1.00,
            brightness = 1.00,
            vibrancy = 0.00,
            vibrancy_darkness = 0.00,
            special = false,
            popups = true,
            popups_ignorealpha = 0.10,
            input_methods = true,
            input_methods_ignorealpha = 0.10
        },
        shadow = {
            enabled = true,
            range = 10,
            render_power = 2,
            sharp = false,
            color = "#00000088",
            offset = "0 0",
            scale = 1.00
        },
        glow = {
            enabled = false,
            range = 5,
            render_power = 3
        }
    },
    group = {
        auto_group = true,
        insert_after_current = true,
        focus_removed_window = true,
        drag_into_group = 1,
        groupbar = {
            enabled = true,
            font_family = "Inter",
            font_size = 14,
            gradients = true,
            height = 32,
            indicator_gap = 0,
            indicator_height = 0,
            stacked = false,
            render_titles = true,
            rounding = 2,
            rounding_power = 2,
            gradient_rounding = 5,
            gradient_rounding_power = 4,
            gradient_round_only_edges = true,
            round_only_edges = false,
            gaps_in = 5,
            gaps_out = 5,
            blur = true,
            keep_upper_gap = false
        },
    },
})
