input {
    kb_model =
    kb_layout = us
    numlock_by_default = true
    repeat_rate = 30
    repeat_delay = 500
    sensitivity = 0.0
    accel_profile = flat
    rotation = 0
    left_handed = false
    natural_scroll = false
    follow_mouse = true

    touchpad {
        disable_while_typing = false
        natural_scroll = true
        clickfinger_behavior = true
    }

}
